import { StoreHub, BatchItem, TransferRecord, AlertItem, HistorySummary } from "./types";

/**
 * 5 Mumbai Operational Dark Store Hubs (Nominal Ground Truth)
 */
export const INITIAL_STORES: StoreHub[] = [
  {
    id: "st-04",
    code: "ST-04",
    name: "Lower Parel Store",
    locality: "Senapati Bapat Marg",
    milkUnits: 4,
    capacity: 30,
    status: "Critical (Runs out in ~4.8h)",
    statusType: "critical",
    nextExpiryHours: 32,
    activeOrders: 18,
  },
  {
    id: "st-02",
    code: "ST-02",
    name: "Bandra West Store",
    locality: "Hill Road / Turner",
    milkUnits: 48,
    capacity: 50,
    status: "Surplus (Can spare 20 units)",
    statusType: "surplus",
    nextExpiryHours: 44,
    activeOrders: 9,
  },
  {
    id: "st-01",
    code: "ST-01",
    name: "Andheri East Store",
    locality: "MIDC Cyber Hub",
    milkUnits: 35,
    capacity: 45,
    status: "Normal",
    statusType: "normal",
    nextExpiryHours: 38,
    activeOrders: 14,
  },
  {
    id: "st-03",
    code: "ST-03",
    name: "Powai Galleria Store",
    locality: "Hiranandani Gardens",
    milkUnits: 28,
    capacity: 35,
    status: "Normal",
    statusType: "normal",
    nextExpiryHours: 42,
    activeOrders: 11,
  },
  {
    id: "st-05",
    code: "ST-05",
    name: "Thane West Store",
    locality: "Ghodbunder Road",
    milkUnits: 25,
    capacity: 35,
    status: "Normal",
    statusType: "normal",
    nextExpiryHours: 48,
    activeOrders: 8,
  },
];

/**
 * Discrete Inventory Batches with FEFO Expiry Priority
 */
export const INITIAL_BATCHES: BatchItem[] = [
  {
    id: "B-MUM-MILK-001",
    storeCode: "ST-04",
    sku: "Amul Taaza Milk 500ml",
    units: 4,
    receivedTime: "Today 05:00 AM",
    expiresInHours: 32,
    fifoPriority: 1,
    state: "fresh",
  },
  {
    id: "B-MUM-MILK-002",
    storeCode: "ST-02",
    sku: "Amul Taaza Milk 500ml",
    units: 20,
    receivedTime: "Today 06:15 AM",
    expiresInHours: 40,
    fifoPriority: 1,
    state: "fresh",
    originCode: "ST-02",
    destCode: "ST-04",
  },
  {
    id: "B-MUM-MILK-003",
    storeCode: "ST-02",
    sku: "Amul Taaza Milk 500ml",
    units: 28,
    receivedTime: "Today 08:30 AM",
    expiresInHours: 48,
    fifoPriority: 2,
    state: "fresh",
  },
  {
    id: "B-MUM-MILK-004",
    storeCode: "ST-01",
    sku: "Amul Taaza Milk 500ml",
    units: 35,
    receivedTime: "Today 07:00 AM",
    expiresInHours: 38,
    fifoPriority: 1,
    state: "fresh",
  },
  {
    id: "B-MUM-MILK-005",
    storeCode: "ST-03",
    sku: "Amul Taaza Milk 500ml",
    units: 28,
    receivedTime: "Today 07:45 AM",
    expiresInHours: 42,
    fifoPriority: 1,
    state: "fresh",
  },
  {
    id: "B-MUM-MILK-006",
    storeCode: "ST-05",
    sku: "Amul Taaza Milk 500ml",
    units: 25,
    receivedTime: "Today 08:00 AM",
    expiresInHours: 48,
    fifoPriority: 1,
    state: "fresh",
  },
];

/**
 * Initial Lateral Fleet Transfers
 */
export const INITIAL_TRANSFERS: TransferRecord[] = [
  {
    id: "TR-101",
    sku: "Amul Taaza Milk 500ml",
    fromCode: "ST-02",
    fromName: "Bandra West",
    toCode: "ST-04",
    toName: "Lower Parel",
    units: 20,
    vanId: "Van #MH-02",
    eta: "10:15 AM (25m)",
    status: "In Transit",
    corridor: "Sea Link Express Route",
    batchId: "B-MUM-MILK-002",
    currentStep: 3,
    etaPassed: true,
    dispatchedAt: "08:15 AM",
  },
  {
    id: "TR-102",
    sku: "Britannia Daily Bread 400g",
    fromCode: "ST-01",
    fromName: "Andheri East",
    toCode: "ST-03",
    toName: "Powai Galleria",
    units: 15,
    vanId: "Van #MH-05",
    eta: "11:30 AM (45m)",
    status: "Staged",
    corridor: "JVLR Cross-Suburban Route",
    currentStep: 1,
    etaPassed: false,
    dispatchedAt: "08:45 AM",
  },
];

/**
 * Default Stock Alerts for Mumbai Network
 */
export const DEFAULT_ALERTS: AlertItem[] = [
  {
    id: "ALERT-01",
    productName: "Amul Taaza Milk 500ml",
    category: "Dairy",
    storeCode: "ST-04",
    storeName: "Lower Parel Store",
    stockOnShelves: 4,
    runsOutInHours: 4.8,
    runsOutAtTime: "1:10 PM",
    orderSpeedPerHour: 0.8,
    urgency: "urgent",
    suggestedAction: "Send 20 Packets from Bandra Store",
    status: "Needs Your Approval",
    sendingStoreCode: "ST-02",
    sendingStoreName: "Bandra West Store",
    transferQuantity: 20,
    senderStartingStock: 48,
    senderLocalDemand: 18,
    moneyAtRisk: 880,
    moneySaved: 700,
    simpleDescription: "Only 4 milk packets left on shelf. Requires quick transfer via Sea Link before lunchtime rush.",
    actionCategory: "TRANSFER",
  },
  {
    id: "ALERT-02",
    productName: "Amul Taaza Milk 500ml",
    category: "Dairy",
    storeCode: "ST-01",
    storeName: "Andheri East Store",
    stockOnShelves: 35,
    runsOutInHours: 7.2,
    runsOutAtTime: "3:30 PM",
    orderSpeedPerHour: 4.2,
    urgency: "moderate",
    suggestedAction: "Monitor Afternoon Orders",
    status: "Watching",
    sendingStoreCode: "ST-02",
    sendingStoreName: "Bandra West Store",
    transferQuantity: 0,
    senderStartingStock: 48,
    senderLocalDemand: 18,
    moneyAtRisk: 0,
    moneySaved: 0,
    simpleDescription: "Stock is steady (35 packets). Afternoon order rate is normal.",
    actionCategory: "MONITOR",
  },
  {
    id: "ALERT-03",
    productName: "Mother Dairy Dahi 400g",
    category: "Dairy",
    storeCode: "ST-03",
    storeName: "Powai Galleria Store",
    stockOnShelves: 14,
    runsOutInHours: 8.5,
    runsOutAtTime: "4:45 PM",
    orderSpeedPerHour: 1.6,
    urgency: "moderate",
    suggestedAction: "Sell with 20% Off Quick Discount",
    status: "Scheduled",
    sendingStoreCode: "ST-03",
    sendingStoreName: "Powai Galleria Store",
    transferQuantity: 0,
    senderStartingStock: 14,
    senderLocalDemand: 8,
    moneyAtRisk: 560,
    moneySaved: 480,
    simpleDescription: "14 pots of dahi will expire by evening. A 20% discount clears all stock before expiry.",
    actionCategory: "DISCOUNT",
  },
  {
    id: "ALERT-04",
    productName: "Farm Fresh Eggs (6 Pack)",
    category: "Produce",
    storeCode: "ST-02",
    storeName: "Bandra West Store",
    stockOnShelves: 45,
    runsOutInHours: 14.0,
    runsOutAtTime: "10:15 PM",
    orderSpeedPerHour: 3.2,
    urgency: "low",
    suggestedAction: "Wait for Warehouse Truck",
    status: "Scheduled",
    sendingStoreCode: "RFC-01",
    sendingStoreName: "Bhiwandi Warehouse",
    transferQuantity: 0,
    senderStartingStock: 45,
    senderLocalDemand: 30,
    moneyAtRisk: 0,
    moneySaved: 0,
    simpleDescription: "Highway delivery running 2 hours late, but store has enough eggs to last through tonight.",
    actionCategory: "PO_WAIT",
  },
  {
    id: "ALERT-05",
    productName: "Britannia Daily Bread 400g",
    category: "Bakery",
    storeCode: "ST-05",
    storeName: "Thane West Store",
    stockOnShelves: 25,
    runsOutInHours: 6.2,
    runsOutAtTime: "2:30 PM",
    orderSpeedPerHour: 3.5,
    urgency: "low",
    suggestedAction: "Watch Evening Tea-Time Orders",
    status: "Watching",
    sendingStoreCode: "ST-03",
    sendingStoreName: "Powai Galleria Store",
    transferQuantity: 0,
    senderStartingStock: 25,
    senderLocalDemand: 16,
    moneyAtRisk: 0,
    moneySaved: 0,
    simpleDescription: "Evening tea rush usually doubles bread orders. Watching Powai store to share bread if needed.",
    actionCategory: "MONITOR",
  },
];

/**
 * Historical Audited Decision Records
 */
export const DEFAULT_HISTORY: HistorySummary = {
  totalDecisions: 5,
  stockoutsPrevented: 2,
  moneySavedInr: 1210,
  accuracyRatePct: 95.8,
  spoilageWasteInr: 240,
  records: [
    {
      id: "OUT-01",
      exceptionTitle: "Amul Taaza Milk 500ml — Fast Orders Alert",
      storeName: "Lower Parel Store",
      productName: "Amul Taaza Milk 500ml",
      actionTaken: "Sent 20 packets from Bandra Store via Van #MH-02",
      outcomeStatus: "Stockout prevented",
      expectedLostUnits: 20,
      actualLostUnits: 0,
      measuredVsExpected: "0 empty shelves vs 20 packets that would have run out",
      wasteUnits: 0,
      wasteValueInr: 0,
      notes: "Van arrived at 10:15 AM via Sea Link. All 20 packets counted and shelved immediately. Zero customer orders lost.",
      evaluatedAt: "Today 11:30 AM",
    },
    {
      id: "OUT-02",
      exceptionTitle: "Mother Dairy Dahi 400g — Close to Expiry",
      storeName: "Powai Galleria Store",
      productName: "Mother Dairy Dahi 400g",
      actionTaken: "20% Flash Discount applied in app",
      outcomeStatus: "Worse than expected",
      expectedLostUnits: 0,
      actualLostUnits: 6,
      measuredVsExpected: "6 packets unsold vs 0 expected",
      wasteUnits: 6,
      wasteValueInr: 240,
      notes: "App discount cleared 14 packets quickly; 6 packets reached expiry before afternoon rush.",
      evaluatedAt: "Today 10:45 AM",
    },
    {
      id: "OUT-03",
      exceptionTitle: "Farm Fresh Eggs (6pk) — Highway Truck Jam",
      storeName: "Bandra West Store",
      productName: "Farm Fresh Eggs (6pk)",
      actionTaken: "Emergency delivery ordered from Nashik depot",
      outcomeStatus: "Residual loss",
      expectedLostUnits: 12,
      actualLostUnits: 4,
      measuredVsExpected: "4 packs lost vs 12 packs without order",
      wasteUnits: 0,
      wasteValueInr: 0,
      notes: "Truck arrived at 1:45 PM. 4 customer orders missed during a 25-minute noon gap before shelves restocked.",
      evaluatedAt: "Today 2:15 PM",
    },
    {
      id: "OUT-04",
      exceptionTitle: "Robusta Bananas (1 doz) — Van Proposal Rejected",
      storeName: "Bandra West Store",
      productName: "Robusta Bananas (1 doz)",
      actionTaken: "Operator decided to hold stock at Bandra",
      outcomeStatus: "Rejected",
      expectedLostUnits: 15,
      actualLostUnits: 14,
      measuredVsExpected: "14 bunches lost (No van was sent)",
      wasteUnits: 0,
      wasteValueInr: 0,
      notes: "Operator chose to keep stock for Bandra shoppers. Baseline runout occurred as predicted.",
      evaluatedAt: "Today 9:20 AM",
    },
    {
      id: "OUT-05",
      exceptionTitle: "Britannia Daily Bread 400g — Evening Rush",
      storeName: "Andheri East Store",
      productName: "Britannia Daily Bread 400g",
      actionTaken: "Sent 20 loaves from Powai Store via Van #MH-05",
      outcomeStatus: "Success",
      expectedLostUnits: 18,
      actualLostUnits: 0,
      measuredVsExpected: "0 empty shelves vs 18 loaves that would have run out",
      wasteUnits: 0,
      wasteValueInr: 0,
      notes: "Dispatched at 5:00 PM, arrived at 5:42 PM. 100% of evening shoppers got their bread.",
      evaluatedAt: "Yesterday 6:30 PM",
    },
  ],
};

