import { Milk, Apple, Egg, Wheat, Droplet, LucideIcon } from "lucide-react";
import { CustomerPersona, DarkStore, RecommendationItem, SimulationEvent } from "./types";

export interface PantryStapleDefinition {
  id: string;
  name: string;
  category: "dairy" | "produce" | "poultry" | "bakery" | "pantry";
  dailyRate: number; // e.g. 0.48 L/day
  unit: string;
  defaultDays: number;
  defaultFillPct: number;
  price: number;
  iconName: "milk" | "apple" | "egg" | "wheat" | "droplet";
}

export const ICON_MAP: Record<string, LucideIcon> = {
  milk: Milk,
  apple: Apple,
  egg: Egg,
  wheat: Wheat,
  droplet: Droplet,
};

export const DEFAULT_PANTRY_STAPLES: PantryStapleDefinition[] = [
  {
    id: "milk",
    name: "Amul Taaza Milk 1L",
    category: "dairy",
    dailyRate: 0.48,
    unit: "L",
    defaultDays: 1,
    defaultFillPct: 15,
    price: 66,
    iconName: "milk",
  },
  {
    id: "tomatoes",
    name: "Fresh Hybrid Tomatoes 500g",
    category: "produce",
    dailyRate: 0.14,
    unit: "kg",
    defaultDays: 1,
    defaultFillPct: 14,
    price: 32,
    iconName: "apple",
  },
  {
    id: "eggs",
    name: "Farm Fresh Eggs (12 pcs)",
    category: "poultry",
    dailyRate: 2.4,
    unit: "pcs",
    defaultDays: 2,
    defaultFillPct: 35,
    price: 90,
    iconName: "egg",
  },
  {
    id: "bread",
    name: "Whole Wheat Bread 400g",
    category: "bakery",
    dailyRate: 0.25,
    unit: "loaves",
    defaultDays: 1,
    defaultFillPct: 10,
    price: 50,
    iconName: "wheat",
  },
  {
    id: "oil",
    name: "Fortune Sunflower Oil 1L",
    category: "pantry",
    dailyRate: 0.04,
    unit: "L",
    defaultDays: 8,
    defaultFillPct: 65,
    price: 50,
    iconName: "wheat",
  },
];

export const SIMULATED_CUSTOMERS: CustomerPersona[] = [
  // Bandra West (St 02)
  {
    id: "cust-karan-sharma",
    name: "Karan Sharma",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Pali Hill, Bandra West, Mumbai",
    avatar: "KS",
    householdSize: 3,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-mehta-family",
    name: "Mehta Family",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Turner Road, Bandra West, Mumbai",
    avatar: "MF",
    householdSize: 4,
    orderFrequencyDays: 2.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-joshi-home",
    name: "Joshi Home",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Perry Cross Road, Bandra West, Mumbai",
    avatar: "JH",
    householdSize: 3,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-khan-household",
    name: "Khan Household",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Carter Road, Bandra West, Mumbai",
    avatar: "KH",
    householdSize: 5,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-desai-family",
    name: "Desai Family",
    homeStoreCode: "St 02",
    homeStoreName: "Bandra West",
    address: "Waterfield Road, Bandra West, Mumbai",
    avatar: "DF",
    householdSize: 2,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Andheri East (St 01)
  {
    id: "cust-sharma-family",
    name: "Sharma Family",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "MIDC Cross Road, Andheri East, Mumbai",
    avatar: "SF",
    householdSize: 4,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-patel-household",
    name: "Priya Patel",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "Chakala, Andheri East, Mumbai",
    avatar: "PP",
    householdSize: 2,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-reddy-home",
    name: "Reddy Home",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "JB Nagar, Andheri East, Mumbai",
    avatar: "RH",
    householdSize: 3,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-singh-family",
    name: "Singh Family",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "Marol Naka, Andheri East, Mumbai",
    avatar: "SF",
    householdSize: 4,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-das-house",
    name: "Das House",
    homeStoreCode: "St 01",
    homeStoreName: "Andheri East",
    address: "Sakinaka Junction, Andheri East, Mumbai",
    avatar: "DH",
    householdSize: 2,
    orderFrequencyDays: 5.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Powai Galleria (St 03)
  {
    id: "cust-gupta-family",
    name: "Gupta Family",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Hiranandani Gardens, Powai, Mumbai",
    avatar: "GF",
    householdSize: 4,
    orderFrequencyDays: 2.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-verma-home",
    name: "Verma Home",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Central Avenue, Powai, Mumbai",
    avatar: "VH",
    householdSize: 3,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-iyer-household",
    name: "Ananya Iyer",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Lake Boulevard, Powai, Mumbai",
    avatar: "AI",
    householdSize: 2,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-bhatt-family",
    name: "Bhatt Family",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "Chandivali Farm Road, Powai, Mumbai",
    avatar: "BF",
    householdSize: 4,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-shetty-house",
    name: "Shetty House",
    homeStoreCode: "St 03",
    homeStoreName: "Powai Galleria",
    address: "JVLR Junction, Powai, Mumbai",
    avatar: "SH",
    householdSize: 3,
    orderFrequencyDays: 5.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Dadar / Lower Parel (St 04)
  {
    id: "cust-kulkarni-family",
    name: "Vikram Kulkarni",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Senapati Bapat Marg, Lower Parel, Mumbai",
    avatar: "VK",
    householdSize: 3,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-thakur-home",
    name: "Thakur Home",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Shivaji Park, Dadar, Mumbai",
    avatar: "TH",
    householdSize: 4,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-rao-household",
    name: "Rao Household",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Prabhadevi, Mumbai",
    avatar: "RH",
    householdSize: 3,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-chopra-family",
    name: "Chopra Family",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Parel Village, Lower Parel, Mumbai",
    avatar: "CF",
    householdSize: 2,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-pillai-house",
    name: "Pillai House",
    homeStoreCode: "St 04",
    homeStoreName: "Dadar / Lower Parel",
    address: "Dadar TT Circle, Mumbai",
    avatar: "PH",
    householdSize: 5,
    orderFrequencyDays: 2.0,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },

  // Thane West (St 05)
  {
    id: "cust-mishra-family",
    name: "Rahul Mishra",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Ghodbunder Road, Thane West, Mumbai",
    avatar: "RM",
    householdSize: 3,
    orderFrequencyDays: 3.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-saxena-home",
    name: "Saxena Home",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Majiwada, Thane West, Mumbai",
    avatar: "SH",
    householdSize: 4,
    orderFrequencyDays: 3.5,
    primaryDepletionItem: "Whole Wheat Bread 400g",
  },
  {
    id: "cust-pandey-household",
    name: "Pandey Household",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Panchpakhadi, Thane West, Mumbai",
    avatar: "PH",
    householdSize: 3,
    orderFrequencyDays: 4.0,
    primaryDepletionItem: "Fresh Hybrid Tomatoes 500g",
  },
  {
    id: "cust-dubey-family",
    name: "Dubey Family",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Vasant Vihar, Thane West, Mumbai",
    avatar: "DF",
    householdSize: 4,
    orderFrequencyDays: 5.0,
    primaryDepletionItem: "Amul Taaza Milk 1L",
  },
  {
    id: "cust-trivedi-house",
    name: "Trivedi House",
    homeStoreCode: "St 05",
    homeStoreName: "Thane West",
    address: "Naupada, Thane West, Mumbai",
    avatar: "TH",
    householdSize: 5,
    orderFrequencyDays: 2.5,
    primaryDepletionItem: "Farm Fresh Eggs (12 pcs)",
  },
];

export const DEFAULT_CUSTOMER_PERSONA: CustomerPersona = SIMULATED_CUSTOMERS[0];

// ---------------------------------------------------------------------------
// Dark Store Network Fleet Topology
// ---------------------------------------------------------------------------

export const INITIAL_STORES: DarkStore[] = [
  {
    id: "st-01",
    code: "St 01",
    name: "Andheri East",
    location: "MIDC Cyber Hub, Mumbai",
    lat: 19.1136,
    lng: 72.8697,
    x: 130,
    y: 110,
    status: "active",
    totalSkus: 25,
    activeBatches: 38,
    stockoutRiskCount: 0,
    spoilageRiskCount: 1,
    excessCapacityUnits: 45,
    inventoryHealth: {
      dairy: 84,
      produce: 72,
      bakery: 90,
      staples: 96,
      packaged: 98,
    },
  },
  {
    id: "st-02",
    code: "St 02",
    name: "Bandra West",
    location: "Hill Road / Turner, Mumbai",
    lat: 19.0596,
    lng: 72.8295,
    x: 90,
    y: 210,
    status: "active",
    totalSkus: 25,
    activeBatches: 42,
    stockoutRiskCount: 0,
    spoilageRiskCount: 0,
    excessCapacityUnits: 60,
    inventoryHealth: {
      dairy: 92,
      produce: 88,
      bakery: 95,
      staples: 100,
      packaged: 100,
    },
  },
  {
    id: "st-03",
    code: "St 03",
    name: "Powai Galleria",
    location: "Hiranandani Gardens, Mumbai",
    lat: 19.1197,
    lng: 72.9051,
    x: 210,
    y: 100,
    status: "active",
    totalSkus: 25,
    activeBatches: 34,
    stockoutRiskCount: 1,
    spoilageRiskCount: 0,
    excessCapacityUnits: 25,
    inventoryHealth: {
      dairy: 68,
      produce: 85,
      bakery: 80,
      staples: 92,
      packaged: 95,
    },
  },
  {
    id: "st-04",
    code: "St 04",
    name: "Dadar / Lower Parel",
    location: "Senapati Bapat Marg, Mumbai",
    lat: 19.0178,
    lng: 72.8478,
    x: 120,
    y: 290,
    status: "critical",
    totalSkus: 25,
    activeBatches: 26,
    stockoutRiskCount: 2,
    spoilageRiskCount: 1,
    excessCapacityUnits: 10,
    inventoryHealth: {
      dairy: 34, // Critical stockout
      produce: 62,
      bakery: 45,
      staples: 88,
      packaged: 90,
    },
  },
  {
    id: "st-05",
    code: "St 05",
    name: "Thane West",
    location: "Ghodbunder Road, Mumbai",
    lat: 19.2183,
    lng: 72.9781,
    x: 250,
    y: 40,
    status: "active",
    totalSkus: 25,
    activeBatches: 40,
    stockoutRiskCount: 0,
    spoilageRiskCount: 2,
    excessCapacityUnits: 55,
    inventoryHealth: {
      dairy: 90,
      produce: 48, // Spoilage alert
      bakery: 85,
      staples: 95,
      packaged: 98,
    },
  },
];

// ---------------------------------------------------------------------------
// Operations Decision Stream Recommendations
// ---------------------------------------------------------------------------

export const INITIAL_RECOMMENDATIONS: RecommendationItem[] = [
  {
    id: "rec-01",
    riskId: "risk-101",
    title: "Projected Stockout: Full Cream Milk 1L",
    productName: "Full Cream Milk",
    productCategory: "dairy",
    sourceStore: {
      id: "st-02",
      code: "St 02",
      name: "Bandra West",
      safeExcess: 28,
    },
    destinationStore: {
      id: "st-04",
      code: "St 04",
      name: "Dadar / Lower Parel",
    },
    actionType: "transfer",
    severity: "critical",
    status: "pending",
    quantity: 20,
    unit: "units",
    distanceKm: 2.1,
    stockoutInHours: 5.2,
    supplierEtaHours: 28.0,
    probability: 0.94,
    confidence: 0.96,
    reasonCodes: [
      "DESTINATION_HIGH_STOCKOUT_RISK",
      "SUPPLIER_LEAD_TIME_EXCEEDS_RUNOUT",
      "SOURCE_HAS_VERIFIED_SAFE_EXCESS",
      "TRANSIT_DISTANCE_UNDER_3KM",
    ],
    alternatives: [
      {
        action: "transfer",
        label: "Lateral Transfer (St 02 → St 04)",
        score: 94,
        reason: "Arrives in 22 mins, covers demand safely, St 02 remains at 140% safety stock.",
        isRecommended: true,
      },
      {
        action: "reorder",
        label: "Emergency Supplier Reorder",
        score: 42,
        reason: "Supplier lead time is 28h, resulting in ~23h of unfulfilled customer orders.",
      },
      {
        action: "hold",
        label: "Hold & Absorb Stockout",
        score: 12,
        reason: "Leaves 38 expected customer stockouts and ~₹2,508 in lost GMV.",
      },
    ],
    tradeoffAnalysis: {
      spoilageAvoidanceINR: 0,
      transportCostINR: 140,
      stockoutLossAvoidedINR: 1320,
      netBenefitINR: 1180,
    },
    createdAt: "2026-08-27T12:00:00Z",
  },
  {
    id: "rec-02",
    riskId: "risk-102",
    title: "Batch Expiry Imminent: Artisan Sourdough",
    productName: "Artisan Sourdough Loaf",
    productCategory: "bakery",
    destinationStore: {
      id: "st-05",
      code: "St 05",
      name: "Thane West",
    },
    actionType: "discount",
    severity: "warning",
    status: "pending",
    quantity: 14,
    unit: "loaves",
    stockoutInHours: 72.0,
    supplierEtaHours: 12.0,
    probability: 0.82,
    confidence: 0.89,
    discountPct: 20,
    reasonCodes: [
      "BATCH_EXPIRY_WITHIN_9_HOURS",
      "HISTORICAL_DEMAND_INSUFFICIENT_FOR_FULL_SELLTHROUGH",
      "20_PCT_DISCOUNT_ACCELERATES_VELOCITY_3X",
    ],
    alternatives: [
      {
        action: "discount",
        label: "Flash Markdown (20% Off)",
        score: 88,
        reason: "Increases hourly sell-through by 280%, preventing full batch write-off.",
        isRecommended: true,
      },
      {
        action: "transfer",
        label: "Inter-store Transfer to Powai",
        score: 51,
        reason: "Transfer transit time (45m) + cold packing reduces net margin below discount yield.",
      },
      {
        action: "hold",
        label: "Hold at Full Price",
        score: 18,
        reason: "Guarantees 11 units spoil at 9:00 PM, resulting in ₹990 direct inventory loss.",
      },
    ],
    tradeoffAnalysis: {
      spoilageAvoidanceINR: 990,
      transportCostINR: 0,
      stockoutLossAvoidedINR: 0,
      netBenefitINR: 792,
    },
    createdAt: "2026-08-27T12:15:00Z",
  },
  {
    id: "rec-03",
    riskId: "risk-103",
    title: "Replenish Staples: Organic Eggs (Pack of 6)",
    productName: "Farm Fresh Eggs 6pk",
    productCategory: "dairy",
    destinationStore: {
      id: "st-03",
      code: "St 03",
      name: "Powai Galleria",
    },
    actionType: "reorder",
    severity: "warning",
    status: "pending",
    quantity: 50,
    unit: "packs",
    stockoutInHours: 18.5,
    supplierEtaHours: 12.0,
    probability: 0.76,
    confidence: 0.92,
    reasonCodes: [
      "STOCKOUT_PROJECTED_IN_18_HOURS",
      "SUPPLIER_ETA_12_HOURS_SAFE_WINDOW",
      "ALL_NEARBY_STORES_BELOW_SAFE_EXCESS_THRESHOLD",
    ],
    alternatives: [
      {
        action: "reorder",
        label: "Batch Supplier Reorder (50 pk)",
        score: 91,
        reason: "Arrives in 12h, well ahead of the 18.5h stockout window. Bulk tier pricing applied.",
        isRecommended: true,
      },
      {
        action: "transfer",
        label: "Lateral Transfer from Andheri",
        score: 35,
        reason: "Andheri safe excess is only 6 packs; would trigger secondary stockout at Andheri.",
      },
      {
        action: "hold",
        label: "Hold & Monitor",
        score: 22,
        reason: "High weekend morning breakfast demand will exhaust stock before midday.",
      },
    ],
    tradeoffAnalysis: {
      spoilageAvoidanceINR: 0,
      transportCostINR: 50,
      stockoutLossAvoidedINR: 3750,
      netBenefitINR: 3700,
    },
    createdAt: "2026-08-27T12:20:00Z",
  },
];

// ---------------------------------------------------------------------------
// Simulation Event Telemetry Feed
// ---------------------------------------------------------------------------

export const INITIAL_EVENTS: SimulationEvent[] = [
  {
    id: "ev-01",
    timestamp: "12:00:03",
    type: "FORECAST_UPDATED",
    description: "Holt double exponential smoothing generated 24h demand matrix across 5 stores.",
    severity: "info",
  },
  {
    id: "ev-02",
    timestamp: "12:00:15",
    type: "RISK_DETECTED",
    description: "CRITICAL stockout alert at Dadar / Lower Parel: Milk 1L runout projected in 5.2h.",
    storeCode: "St 04",
    severity: "critical",
  },
  {
    id: "ev-03",
    timestamp: "12:00:22",
    type: "RECOMMENDATION_CREATED",
    description: "Generated TRANSFER recommendation: 20 units from Bandra West (St 02) to Dadar (St 04).",
    storeCode: "St 04",
    severity: "warning",
  },
  {
    id: "ev-04",
    timestamp: "12:15:05",
    type: "RISK_DETECTED",
    description: "SPOILAGE alert at Thane West: 14 loaves Artisan Sourdough expiring in <9h.",
    storeCode: "St 05",
    severity: "warning",
  },
  {
    id: "ev-05",
    timestamp: "12:15:10",
    type: "RECOMMENDATION_CREATED",
    description: "Generated DISCOUNT recommendation: 20% flash markdown on Artisan Sourdough.",
    storeCode: "St 05",
    severity: "info",
  },
];


