import { DarkStore, RecommendationItem, SimulationEvent } from "./types";

// ---------------------------------------------------------------------------
// Dark Store Network Fleet Topology
// ---------------------------------------------------------------------------

export const INITIAL_STORES: DarkStore[] = [
  {
    id: "st-01",
    code: "St 01",
    name: "Andheri East",
    location: "MIDC Cyber Hub, Mumbai",
    lat: 19.1136,
    lng: 72.8697,
    x: 130,
    y: 110,
    status: "active",
    totalSkus: 25,
    activeBatches: 38,
    stockoutRiskCount: 0,
    spoilageRiskCount: 1,
    excessCapacityUnits: 45,
    inventoryHealth: {
      dairy: 84,
      produce: 72,
      bakery: 90,
      staples: 96,
      packaged: 98,
    },
  },
  {
    id: "st-02",
    code: "St 02",
    name: "Bandra West",
    location: "Hill Road / Turner, Mumbai",
    lat: 19.0596,
    lng: 72.8295,
    x: 90,
    y: 210,
    status: "active",
    totalSkus: 25,
    activeBatches: 42,
    stockoutRiskCount: 0,
    spoilageRiskCount: 0,
    excessCapacityUnits: 60,
    inventoryHealth: {
      dairy: 92,
      produce: 88,
      bakery: 95,
      staples: 100,
      packaged: 100,
    },
  },
  {
    id: "st-03",
    code: "St 03",
    name: "Powai Galleria",
    location: "Hiranandani Gardens, Mumbai",
    lat: 19.1197,
    lng: 72.9051,
    x: 210,
    y: 100,
    status: "active",
    totalSkus: 25,
    activeBatches: 34,
    stockoutRiskCount: 1,
    spoilageRiskCount: 0,
    excessCapacityUnits: 25,
    inventoryHealth: {
      dairy: 68,
      produce: 85,
      bakery: 80,
      staples: 92,
      packaged: 95,
    },
  },
  {
    id: "st-04",
    code: "St 04",
    name: "Dadar / Lower Parel",
    location: "Senapati Bapat Marg, Mumbai",
    lat: 19.0178,
    lng: 72.8478,
    x: 120,
    y: 290,
    status: "critical",
    totalSkus: 25,
    activeBatches: 26,
    stockoutRiskCount: 2,
    spoilageRiskCount: 1,
    excessCapacityUnits: 10,
    inventoryHealth: {
      dairy: 34, // Critical stockout
      produce: 62,
      bakery: 45,
      staples: 88,
      packaged: 90,
    },
  },
  {
    id: "st-05",
    code: "St 05",
    name: "Thane West",
    location: "Ghodbunder Road, Mumbai",
    lat: 19.2183,
    lng: 72.9781,
    x: 250,
    y: 40,
    status: "active",
    totalSkus: 25,
    activeBatches: 40,
    stockoutRiskCount: 0,
    spoilageRiskCount: 2,
    excessCapacityUnits: 55,
    inventoryHealth: {
      dairy: 90,
      produce: 48, // Spoilage alert
      bakery: 85,
      staples: 95,
      packaged: 98,
    },
  },
];

// ---------------------------------------------------------------------------
// Operations Decision Stream Recommendations
// ---------------------------------------------------------------------------

export const INITIAL_RECOMMENDATIONS: RecommendationItem[] = [
  {
    id: "rec-01",
    riskId: "risk-101",
    title: "Projected Stockout: Full Cream Milk 1L",
    productName: "Full Cream Milk",
    productCategory: "dairy",
    sourceStore: {
      id: "st-02",
      code: "St 02",
      name: "Bandra West",
      safeExcess: 28,
    },
    destinationStore: {
      id: "st-04",
      code: "St 04",
      name: "Dadar / Lower Parel",
    },
    actionType: "transfer",
    severity: "critical",
    status: "pending",
    quantity: 20,
    unit: "units",
    distanceKm: 2.1,
    stockoutInHours: 5.2,
    supplierEtaHours: 28.0,
    probability: 0.94,
    confidence: 0.96,
    reasonCodes: [
      "DESTINATION_HIGH_STOCKOUT_RISK",
      "SUPPLIER_LEAD_TIME_EXCEEDS_RUNOUT",
      "SOURCE_HAS_VERIFIED_SAFE_EXCESS",
      "TRANSIT_DISTANCE_UNDER_3KM",
    ],
    alternatives: [
      {
        action: "transfer",
        label: "Lateral Transfer (St 02 → St 04)",
        score: 94,
        reason: "Arrives in 22 mins, covers demand safely, St 02 remains at 140% safety stock.",
        isRecommended: true,
      },
      {
        action: "reorder",
        label: "Emergency RFC Reorder",
        score: 42,
        reason: "RFC lead time is 28h, resulting in ~23h of unfulfilled customer orders.",
      },
      {
        action: "hold",
        label: "Hold & Absorb Stockout",
        score: 12,
        reason: "Leaves 38 expected customer stockouts and ~₹2,508 in lost GMV.",
      },
    ],
    tradeoffAnalysis: {
      spoilageAvoidanceINR: 0,
      transportCostINR: 140,
      stockoutLossAvoidedINR: 1320,
      netBenefitINR: 1180,
    },
    createdAt: "2026-08-27T12:00:00Z",
  },
  {
    id: "rec-02",
    riskId: "risk-102",
    title: "Batch Expiry Imminent: Artisan Sourdough",
    productName: "Artisan Sourdough Loaf",
    productCategory: "bakery",
    destinationStore: {
      id: "st-05",
      code: "St 05",
      name: "Thane West",
    },
    actionType: "discount",
    severity: "warning",
    status: "pending",
    quantity: 14,
    unit: "loaves",
    stockoutInHours: 72.0,
    supplierEtaHours: 12.0,
    probability: 0.82,
    confidence: 0.89,
    discountPct: 20,
    reasonCodes: [
      "BATCH_EXPIRY_WITHIN_9_HOURS",
      "HISTORICAL_DEMAND_INSUFFICIENT_FOR_FULL_SELLTHROUGH",
      "20_PCT_DISCOUNT_ACCELERATES_VELOCITY_3X",
    ],
    alternatives: [
      {
        action: "discount",
        label: "Flash Markdown (20% Off)",
        score: 88,
        reason: "Increases hourly sell-through by 280%, preventing full batch write-off.",
        isRecommended: true,
      },
      {
        action: "transfer",
        label: "Inter-store Transfer to Powai",
        score: 51,
        reason: "Transfer transit time (45m) + cold packing reduces net margin below discount yield.",
      },
      {
        action: "hold",
        label: "Hold at Full Price",
        score: 18,
        reason: "Guarantees 11 units spoil at 9:00 PM, resulting in ₹990 direct inventory loss.",
      },
    ],
    tradeoffAnalysis: {
      spoilageAvoidanceINR: 990,
      transportCostINR: 0,
      stockoutLossAvoidedINR: 0,
      netBenefitINR: 792,
    },
    createdAt: "2026-08-27T12:15:00Z",
  },
  {
    id: "rec-03",
    riskId: "risk-103",
    title: "Replenish Staples: Organic Eggs (Pack of 6)",
    productName: "Farm Fresh Eggs 6pk",
    productCategory: "dairy",
    destinationStore: {
      id: "st-03",
      code: "St 03",
      name: "Powai Galleria",
    },
    actionType: "reorder",
    severity: "warning",
    status: "pending",
    quantity: 50,
    unit: "packs",
    stockoutInHours: 18.5,
    supplierEtaHours: 12.0,
    probability: 0.76,
    confidence: 0.92,
    reasonCodes: [
      "STOCKOUT_PROJECTED_IN_18_HOURS",
      "SUPPLIER_ETA_12_HOURS_SAFE_WINDOW",
      "ALL_NEARBY_STORES_BELOW_SAFE_EXCESS_THRESHOLD",
    ],
    alternatives: [
      {
        action: "reorder",
        label: "RFC Reorder (50 pk)",
        score: 91,
        reason: "Arrives in 12h, well ahead of the 18.5h stockout window. Bulk tier pricing applied.",
        isRecommended: true,
      },
      {
        action: "transfer",
        label: "Lateral Transfer from Andheri",
        score: 35,
        reason: "Andheri safe excess is only 6 packs; would trigger secondary stockout at Andheri.",
      },
      {
        action: "hold",
        label: "Hold & Monitor",
        score: 22,
        reason: "High weekend morning breakfast demand will exhaust stock before midday.",
      },
    ],
    tradeoffAnalysis: {
      spoilageAvoidanceINR: 0,
      transportCostINR: 50,
      stockoutLossAvoidedINR: 3750,
      netBenefitINR: 3700,
    },
    createdAt: "2026-08-27T12:20:00Z",
  },
];

// ---------------------------------------------------------------------------
// Simulation Event Telemetry Feed
// ---------------------------------------------------------------------------

export const INITIAL_EVENTS: SimulationEvent[] = [
  {
    id: "ev-01",
    timestamp: "12:00:03",
    type: "FORECAST_UPDATED",
    description: "Holt double exponential smoothing generated 24h demand matrix across 5 stores.",
    severity: "info",
  },
  {
    id: "ev-02",
    timestamp: "12:00:15",
    type: "RISK_DETECTED",
    description: "CRITICAL stockout alert at Dadar / Lower Parel: Milk 1L runout projected in 5.2h.",
    storeCode: "St 04",
    severity: "critical",
  },
  {
    id: "ev-03",
    timestamp: "12:00:22",
    type: "RECOMMENDATION_CREATED",
    description: "Generated TRANSFER recommendation: 20 units from Bandra West (St 02) to Dadar (St 04).",
    storeCode: "St 04",
    severity: "warning",
  },
  {
    id: "ev-04",
    timestamp: "12:15:05",
    type: "RISK_DETECTED",
    description: "SPOILAGE alert at Thane West: 14 loaves Artisan Sourdough expiring in <9h.",
    storeCode: "St 05",
    severity: "warning",
  },
  {
    id: "ev-05",
    timestamp: "12:15:10",
    type: "RECOMMENDATION_CREATED",
    description: "Generated DISCOUNT recommendation: 20% flash markdown on Artisan Sourdough.",
    storeCode: "St 05",
    severity: "info",
  },
];


